version: '3.8'

services:
  mysql-container:
    build:
      context: ./mysql-container
      dockerfile: Dockerfile
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: operations_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    networks:
      - app-network

  webapp-container:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webapp-container
    ports:
      - "8888:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mysql-container
    networks:
      - app-network

networks:
  app-network:
    driver: bridge